# Generated by Django 4.0.4 on 2022-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationperm',
            name='ncar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='applicationperm',
            name='shipmentrequest',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='applicationperm',
            name='travelrequest',
            field=models.BooleanField(),
        ),
    ]
