# Generated by Django 4.0.4 on 2023-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftplink', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
