# Generated by Django 4.0.4 on 2022-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetnum', models.CharField(blank=True, max_length=50, null=True)),
                ('assettagno', models.CharField(blank=True, max_length=50, null=True)),
                ('assetinvdate', models.DateField(blank=True, null=True)),
                ('assetinvno', models.CharField(blank=True, max_length=50, null=True)),
                ('assetponumber', models.CharField(blank=True, max_length=50, null=True)),
                ('assetcost', models.CharField(blank=True, max_length=20, null=True)),
                ('assetcc', models.CharField(blank=True, max_length=10, null=True)),
                ('assetstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compmodel', models.CharField(blank=True, max_length=100, null=True)),
                ('compbrand', models.CharField(blank=True, max_length=50, null=True)),
                ('compserialnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('compprocessor', models.CharField(blank=True, max_length=20, null=True)),
                ('compgraphic', models.CharField(blank=True, max_length=50, null=True)),
                ('compram', models.CharField(blank=True, max_length=20, null=True)),
                ('compstorage', models.CharField(blank=True, max_length=20, null=True)),
                ('compos', models.CharField(blank=True, max_length=20, null=True)),
                ('compdisplay', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('owner1', models.CharField(blank=True, max_length=150, null=True)),
                ('owner2', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
