# Generated by Django 4.0.4 on 2022-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caltarget',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misc',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
