# Generated by Django 4.0.4 on 2023-02-27 09:35

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optic',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/optic'),
        ),
    ]
