# Generated by Django 4.0.4 on 2023-02-27 15:46

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0002_alter_optic_itempic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/cable'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/cable'),
        ),
        migrations.AlterField(
            model_name='caltarget',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/caltarget'),
        ),
        migrations.AlterField(
            model_name='caltarget',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/caltarget'),
        ),
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/card'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/laser'),
        ),
        migrations.AlterField(
            model_name='laser',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/laser'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/misc'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/misc'),
        ),
        migrations.AlterField(
            model_name='optic',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/optic'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/power'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/power'),
        ),
    ]
