# Generated by Django 4.0.4 on 2022-12-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0003_remove_cable_quantityaval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lens',
            old_name='focallenth',
            new_name='focallength',
        ),
    ]
