# Generated by Django 4.0.4 on 2022-12-23 07:40

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0006_alter_camera_itempic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='doc'),
        ),
    ]
