# Generated by Django 4.0.4 on 2022-12-29 09:21

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0010_alter_lightingcon_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/lightingcontroller'),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/lightingcontroller'),
        ),
    ]
