# Generated by Django 4.0.4 on 2022-12-29 09:22

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0011_alter_lighting_attachment_alter_lighting_itempic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='attachment/lighting'),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='itempic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos/lighting'),
        ),
    ]
