# Generated by Django 4.0.4 on 2022-12-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labassets', '0012_alter_lighting_attachment_alter_lighting_itempic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='manufacturing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
