# Generated by Django 4.0.4 on 2022-05-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvrequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelinfo',
            old_name='company_name',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='travelinfo',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='travelinfo',
            old_name='customer_name',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='travelinfo',
            old_name='director_approval',
            new_name='directorapproval',
        ),
        migrations.RenameField(
            model_name='travelinfo',
            old_name='travel_purpose',
            new_name='travelpurpose',
        ),
        migrations.RenameField(
            model_name='travelinfo',
            old_name='updated_at',
            new_name='updatedat',
        ),
    ]
