# Generated by Django 4.0.4 on 2022-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinfo',
            name='hodapproval',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
