# Generated by Django 4.0.4 on 2022-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvrequest', '0002_alter_travelinfo_hodapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aknowlegdeticket',
            name='carchoose',
        ),
        migrations.RemoveField(
            model_name='aknowlegdeticket',
            name='carplateno',
        ),
        migrations.RemoveField(
            model_name='aknowlegdeticket',
            name='cartype',
        ),
        migrations.AddField(
            model_name='aknowlegdeticket',
            name='issuefile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
