# Generated by Django 4.0.4 on 2022-07-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvrequest', '0004_remove_aknowlegdeticket_issuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aknowlegdeticket',
            name='issuetdestination',
        ),
    ]
